version: '3'
services:
  mc:
    build: .
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
    - ./server/worlds/:/worlds
    - ./server/server.properties:/server.properties
